language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alikureishy/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true alikureishy/docker-react npm run test